### ISSUE TITLE
About weight files

### ISSUE THREAD

**Issue by wangzhaoyang-508** [IDEA-Research/detrex-storage#1]
Why does the dino_r50_4scale_12ep.pth only 182MB，but the dino_r50_5scale_12ep.pth is much bigger than that？

**Comment by rentainhe** [comment]
> Why does the dino_r50_4scale_12ep.pth only 182MB，but the dino_r50_5scale_12ep.pth is much bigger than that？

Sry for missing this issue before, this is because we forgot to move the optimizer state in some checkpoints which may increase the weight size

**Comment by rentainhe** [comment]
> > Why does the dino_r50_4scale_12ep.pth only 182MB，but the dino_r50_5scale_12ep.pth is much bigger than that？
> 
> Sry for missing this issue before, this is because we forgot to move the optimizer state in some checkpoints which may increase the weight size

for some larger model as `Swin-Large-DINO`, we will remove the optimizer state to make it smaller enough for the git storage

**Comment by rentainhe** [comment]
I'm closing this issue~ feel free to reopen it if needed

**Comment by Freyglenn** [comment]
```
Kkk
```
